# https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test-cert-manager-service-account
  namespace: default
  labels:
    app: e2e-test-cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-test-cert-manager-cluster-role
  namespace: default
  labels:
    app: e2e-test-cert-manager
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["certificates.k8s.io"]
    resources: 
      - "certificatesigningrequests/status"
      - "certificatesigningrequests/approval"
      - "signers"
    verbs: ["update", "approve"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch"]
  - apiGroups: [""] 
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kubelet-serving
    verbs:
      - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-test-cert-manager-role-binding
  namespace: default
  labels:
    app: e2e-test-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e-test-cert-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: e2e-test-cert-manager-service-account
    namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-test-cert-manager-setup
  namespace: default
  labels:
    app: e2e-test-cert-manager
spec:
  template:
    metadata:
      namespace: default
    spec:
      serviceAccountName: e2e-test-cert-manager-service-account
      containers:
      - name: metadata-cert-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        # Use the commit hash so we always use the image we built
        image: newrelic/k8s-webhook-cert-manager:e2e-test
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "no-service"
          - "--webhook"
          - "e2e-test-cert-manager-webhook"
          - "--secret"
          - "e2e-test-cert-manager-secret"
          - "--namespace"
          - "default"
      restartPolicy: Never
  backoffLimit: 1
