blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/k8s-webhook-cert-manager/blob/master/README.md#support
    about: Check out the README for troubleshooting directions
